### ISSUE TITLE
error at CollectGCBiasMetrics step

### ISSUE THREAD

**Issue by DoaneAS** [kundajelab/bds_atac#22]
Hi,
Thanks for putting together this pipeline, and especially for including IDR in the processing.
 
I get the following error and wonder if someone could point me in the right direction to investigate the cause.  Looks like a JAVA issue, though maybe R related.  Not sure what it's trying to do at this stage.

> StdErr (100000000 lines)  :
> 		Picked up _JAVA_OPTIONS: -Xms256M -Xmx10G -XX:ParallelGCThreads=1
> 		Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 142535482
> 			at picard.analysis.CollectGcBiasMetrics.doWork(CollectGcBiasMetrics.java:175)
> 			at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:187)
> 			at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:89)
> 			at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:99)
> 		Picked up _JAVA_OPTIONS: -Xms256M -Xmx10G -XX:ParallelGCThreads=1
> 		[bam_sort_core] merging from 50 files...
> 		[bam_sort_core] merging from 47 files...
> 		Picked up _JAVA_OPTIONS: -Xms256M -Xmx10G -XX:ParallelGCThreads=1
> 		Picked up _JAVA_OPTIONS: -Xms256M -Xmx10G -XX:ParallelGCThreads=1
> 		ERROR	2016-07-20 11:16:55	ProcessExecutor	Bioconductor version 3.2 (BiocInstaller 1.20.3), ?biocLite for help
> 		ERROR	2016-07-20 11:16:55	ProcessExecutor	A new version of Bioconductor is available after installing the most recent
> 		ERROR	2016-07-20 11:16:55	ProcessExecutor	  version of R; see http://bioconductor.org/install
> 		processing chromosomes
> 		/zenodotus/dat01/melnick_bcell_scratch/asd2007/bin/bds_atac/ataqc/run_ataqc.py:911: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
> 		  sorted_results = merged.sort('corr', ascending=True)
> 		Traceback (most recent call last):
> 		  File "/zenodotus/dat01/melnick_bcell_scratch/asd2007/bin/bds_atac/ataqc/run_ataqc.py", line 1589, in <module>
> 		    main()
> 		  File "/zenodotus/dat01/melnick_bcell_scratch/asd2007/bin/bds_atac/ataqc/run_ataqc.py", line 1538, in main
> 		    ('gc_bias', plot_gc(gc_out)),
> 		  File "/xx/bds_atac/ataqc/run_ataqc.py", line 209, in plot_gc
> 		    with open(data_file) as fp:
> 		IOError: [Errno 2] No such file or directory: '/xx/ATACcore/run/Sample_TS021/out/qc/rep1/TS021_fresh_5min_pooled_R1.PE2SE_gc.txt'`

Thanks

**Comment by akundaje** [comment]
Thanks. We'll look into it.

Anshul
